#pragma once
//types of tiles on grid
enum TileTypes 
{
	INVALID_TILE_TYPE = -1,
	EMPTY_TILE,
	SNAKE_TILE,
	FOOD_TILE,
	SPEED_DOWN_TILE,
	SPEED_UP_TILE,
	EXTRA_POINTS_TILE,
	WALL_TILE,
	NUM_TILE_TYPES
};