#ifndef GAME_EVENT_H
#define GAME_EVENT_H
#include "Event.h"

enum GameEventType
{
	INIT_SMURF_EVENT = NUM_EVENT_TYPES,
	DESTROY_SMURF_EVENT,
	SWAP_SMURF_ANIMATION_EVENT,
	TOGGLE_SMURF_ANIMATIONS_EVENT,
	EXIT_GAME_EVENT
};
#endif